# Generated by Django 5.1.5 on 2025-02-25 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_medication_description_medication_dosage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medication',
            name='dosage',
            field=models.CharField(default='Unknown', max_length=50),
        ),
    ]
